sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t davidgibbsig/docker-alpine-miniconda2 .

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push davidgibbsig/docker-alpine-miniconda2